[project]
name = "librarecipes"
version = "2.0.1"
description = ""
authors = [
    {name = "Adrien PAJON",email = "adrien.pajon@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit (>=1.46.1,<2.0.0)",
    "sqlalchemy (>=2.0.41,<3.0.0)",
    "streamlit-tags (>=1.2.8,<2.0.0)"
]


[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
black = "^25.1.0"
mypy = "^1.16.1"
pyright = "^1.1.402"
pylint = "^3.3.7"
pydocstyle = "^6.3.0"
pre-commit = "^4.2.0"
pytest = "^8.4.1"
pytest-stub = "^1.1.0"
autopep8 = "^2.3.2"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
