// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        // Primary repositories
        maven { url "https://maven.google.com" }
        google()
        mavenCentral()
        
        // Fallback repositories
        gradlePluginPortal()
        
        // Local repository as last resort
        mavenLocal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22'
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.48'
    }
}

