name: CI - Python (Poetry)

on:
  push:
    branches-ignore: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false  # pour installer dans l'env global du runner

      - name: Install dependencies
        run: |
          poetry install

      - name: Run tests
        run: |
          poetry run pytest -q

      - name: Lint
        run: |
          poetry run flake8 .
